version: '3.8'

services:
  backend:
    build:
      context: ./Techdome-backend
    ports:
      - "5000:3000"
    environment:
    - DB =postgresql://user:password@db:5432/mydb
    depends_on:
      - db

  frontend:
    build:
      context: ./Techdome-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

